# The content of this file will be appended to the keyboard layout.
# For example if you uncomment the following lines Alt+j can be used
# to go to the next console and Alt+k can be used to go to the
# previous console:

# alt keycode 36 = Incr_Console
# shiftl alt keycode 36 = Incr_Console
# shiftr alt keycode 36 = Incr_Console
# shiftr shiftl alt keycode 36 = Incr_Console
# ctrll alt keycode 36 = Incr_Console
# ctrll shiftl alt keycode 36 = Incr_Console
# ctrll shiftr alt keycode 36 = Incr_Console
# ctrll shiftr shiftl alt keycode 36 = Incr_Console

# alt keycode 37 = Decr_Console
# shiftl alt keycode 37 = Decr_Console
# shiftr alt keycode 37 = Decr_Console
# shiftr shiftl alt keycode 37 = Decr_Console
# ctrll alt keycode 37 = Decr_Console
# ctrll shiftl alt keycode 37 = Decr_Console
# ctrll shiftr alt keycode 37 = Decr_Console
# ctrll shiftr shiftl alt keycode 37 = Decr_Console

